export const images = {
  logo: "/assets/logo-rec.webp",
  hero: "/assets/hero.png",
  serviceHead:
    "https://proactiveforher.com/static/media/platform.ac28d72b.webp",
  gmpImage: "/assets/gmpimg.webp",
  testimonial1: "/assets/testimonial1.webp",
  testimonial2: "/assets/testimonial2.webp",
  testimonial3: "/assets/testimonial3.webp",
  testimonial4: "/assets/testimonial4.webp",
  helps1: "/assets/sugar.webp",
  helps2: "/assets/syringe.webp",
  helps3: "/assets/bloodcells.webp",
  helps4: "/assets/heart.webp",
  helps5: "/assets/oil.webp",
  helps6: "/assets/inflame.webp",
  sourced: "/assets/bg-nature.webp",
  neem: "/assets/neem.webp",
  amla: "/assets/amla.webp",
  jamunn: "/assets/jamun.webp",
  chirata: "/assets/chirata.webp",
  gudmar: "/assets/gudmar.webp",
  ajwain: "/assets/ajwain.webp",
  tulsi: "/assets/tulsi.webp",
  karela: "/assets/karela.webp",
  methika: "/assets/methika.webp",
  amla: "/assets/amla.webp",
};
