const SHOPIFY_STOREFRONT_ACCESSTOKEN = "f023386bb26bfdaa01b3e82ceba24f7c";
const SHOPIFY_STORE_DOMAIN = "vedicelement.myshopify.com";

export { SHOPIFY_STOREFRONT_ACCESSTOKEN, SHOPIFY_STORE_DOMAIN };
